mestadels CSS förändringar, med HTML anpassningar
erik-gullberg-devoteam/sparmen-v2 pull request #4
Opened 2024-07-08 20:37 UTC by theolli999

Saker att se över:

- Blev ganska snabbt förvirrad över alla olika css filer, vet inte om allt ligger där det ska
- Under sommarspexet märktes det att siffrorna var nödvändiga. Lade till för spex, men funkade inte för kupletter.  Det verkar vara en backend lösning som krävs för det.
- Siffrorna i orginal-spärmen och nya spärmen är inte samma. Detta bör också fixas i backend. 

Finns lite småpill jag vill göra. Samt få feedback från dig. Sen kan vi ta det till resten av gruppen och se vad dem tycker

2024-07-09 08:41 UTC, erik-gullberg-devoteam commented
Någonting har troligtvis gått fel när main mergades in. Om man söker på något kraschar applikationen med detta felmeddelande som även är anledningen till att deployen failar ovan.

![Screenshot 2024-07-09 at 10 36 59 AM](https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/9384e582-c2be-470a-9997-d885216db44d)

2024-07-09 09:09 UTC, erik-gullberg-devoteam requested changes

2024-07-09 09:09 UTC, erik-gullberg-devoteam commented on src/app/spex/[id]/page.module.css
>  .statusBar {
Det går även att öppna flera låtar på en gång och lägga flera av dessa element ovanpå varandra. Så länge man kan ha flera låtar öppna bör vi inte ha en flygande status bar eftersom vi inte kan veta vilken låt användaren tittar på.

2024-07-09 09:09 UTC, erik-gullberg-devoteam commented on src/app/spex/[id]/page.module.css
>  .statusBar {
Men generellt att täcka upp text med ett stort element tror jag inte är en så bra idé. Texten är det viktigaste innehållet på sidan så hade hellre velat se en annan lösning.

2024-07-09 09:13 UTC, erik-gullberg-devoteam commented on src/app/globals.css
> +  --background-start-rgb: 40, 40, 40;
Denna gradient-bakgrunden gör att hela bakgrunden ändras och blir ljusare varje gång man öppnar en låt.

<img width="897" alt="Screenshot 2024-07-09 at 11 11 24 AM" src="https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/d63dbb67-8e0d-46f8-b93b-3e401a3fbaa7">
<img width="819" alt="Screenshot 2024-07-09 at 11 11 35 AM" src="https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/e7812125-e693-4e5c-8d77-fb8938a9d1d0">
<img width="814" alt="Screenshot 2024-07-09 at 11 11 49 AM" src="https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/6011742b-e74e-4acf-92df-2f92f4c8b8e6">

2024-07-09 09:18 UTC, erik-gullberg-devoteam commented
Ang, låtnummer så lade jag till det i main igår. Kolla så det ser rätt ut.
Att siffrorna stämmer över med gamla spärmen tycker jag spontant inte är viktigt. Kan läggas till men värdet känns väldigt litet.

2024-07-09 17:55 UTC, theolli999 commented on src/app/spex/[id]/page.module.css
>  .statusBar {
Fixat denna nu, förutom admin-vyn. Den kan jag inte se då jag inte är admin så då är det svårt att fixa det. Du går gärna göra mitt konto till admin

2024-07-09 18:10 UTC, erik-gullberg-devoteam commented on src/app/spex/[id]/page.module.css
>  .statusBar {
done!

2024-07-09 18:43 UTC, erik-gullberg-devoteam reviewed
Snyggt fixat. Ligger autodeployat här för tilfället: https://sparmen-v2-git-initial-visual-changes-erik-gullbergs-projects.vercel.app/spex/2?_vercel_share=fsn6iTXaH5pokmydEZoL0cPzzDKE9636

Jag är fortfarande inte helt nöjd med status baren. Den ser out of place ut med den starka gula färgen. 
Märkte nu om man inte är inloggad försvinner också rösta-knappen vilket gör att man inte riktigt fattar vad siffran är.

<img width="621" alt="Screenshot 2024-07-09 at 8 37 29 PM" src="https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/7f259a45-0f05-4636-9053-b2ed8139c92d">

2024-07-09 18:46 UTC, erik-gullberg-devoteam commented
Verkar också som att numreringen av låtarna inne på en föreställning har försvunnit.

2024-07-09 19:14 UTC, theolli999 commented
Fixade till en transparant bakgrund. Håller med om att den gula färgen kanske inte va så snygg, men tyckte den va lite spexig iaf. Nu ser det mer tråkigt, men stilrent enligt mig.

2024-07-09 23:08 UTC, erik-gullberg-devoteam commented
> Fixade till en transparant bakgrund. Håller med om att den gula färgen kanske inte va så snygg, men tyckte den va lite spexig iaf. Nu ser det mer tråkigt, men stilrent enligt mig.

Stilrent är inte ordet jag skulle använda.

- Knapparna sitter långt ifrån varandra vilket utan inramning ser konstigt ut
- Mix av vit och svart text
- Låg kontrast med det svarta på det grå så man ser inte rating tydligt
- Man kan inte se rating utan att vara inloggad 
- Länk-knappen tar rösta knappens plats om man inte är inloggad

![Screenshot 2024-07-10 at 12 44 25 AM](https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/83a1977a-b7b3-428e-af3e-fd58145bb6b2)

![Screenshot 2024-07-10 at 12 45 19 AM](https://github.com/erik-gullberg-devoteam/sparmen-v2/assets/126695088/867bb44f-fa85-44f7-b099-1f154d991767)

Om du inte pallar så bara revertera statusBar till wireframe designen i main.
Annars ser allt bra ut från min sida. Så när detta är gjort så kan vi låta resten titta på det.

2024-07-10 08:42 UTC, theolli999 commented
Du kan ändra tillbaka om du vill. Håller med om dina kommentarer, men gillade inte den första designen heller. Kanske ger det ett nytt försök att designar den på ett snyggare sätt någon annan gång

2024-07-10 11:52 UTC, erik-gullberg-devoteam approved these changes

2024-07-10 11:52 UTC, merged